### ISSUE TITLE
Improvements for tests/ci.sh

### ISSUE THREAD

**Issue by anta5010** [parallaxsecond/parsec#108]
It might be useful to use tests/ci.sh for manual testing. But, to be able to do that we can make some improvements. For example:
1. The script can't be run more than once in some cases because:
   - For TPM and "all" providers tests tpm_server is started, but not stopped
   - For the PKCS11 and "all" providers find_slot_number.sh is run. This script adds a line to config.toml without checking if the line exists already and parsec fails to start. 
2. Parsec status is not checked after "cargo run" and "cargo test" is run even if parsec failed to start.
3. If possible we should replace all the hard-coded timeouts  with waiting for an event.
4. May be make "cargo clean" optional

**Comment by ionut-arm** [comment]
The points sound compelling, the reason for most of those is that the script was mainly intended to be run for CI purposes, but I think it makes sense to convert it into a "test-running script". 

I'm not sure if it would be worth the time investment into making it a python script instead of bash - more versatile and probably easier to work with for the future, but some cost involved in actually converting the whole thing.

**Comment by anta5010** [comment]
The script mostly runs commands, so I don't think it's worth converting to python

**Comment by hug-dev** [comment]
Seems like pretty good improvements!

> 2. Parsec status is not checked after "cargo run" and "cargo test" is run even if parsec failed to start.
> 3. If possible we should replace all the hard-coded timeouts with waiting for an event.

It would be nice indeed to find a way of checking Parsec status instead of just waiting a hard-coded timeout. That would address those two issues.
One idea would be to have a special test target in the client that tries to perform `Ping` requests until it works?

**Comment by anta5010** [comment]
https://github.com/parallaxsecond/parsec/pull/117
