### ISSUE TITLE
Add more Fixed Common header tests

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec#351]
The book describes some conditions for the valid values of some fields, [on this page](https://parallaxsecond.github.io/parsec-book/parsec_client/wire_protocol.html#the-fixed-common-header).

We should add some sanity checks [in this file](https://github.com/parallaxsecond/parsec/blob/master/e2e_tests/tests/per_provider/normal_tests/basic.rs) making sure that:
* an error is returned if fields have illegal values for requests
* response fields are always correct

**Comment by ionut-arm** [comment]
I'm ok with adding more E2E tests for this, but they should not be the primary way we verify this alignment (mostly because we're not directly testing the code responsible for handling those cases here).

The interface code that handles conversion to/from wire protocol is [here](https://github.com/parallaxsecond/parsec-interface-rs/blob/master/src/requests/common/wire_header_1_0.rs) - we need to have tests for all the conditions in `read_from_stream`.

**Comment by hug-dev** [comment]
Done in #440
