### ISSUE TITLE
If a response is an error, log it before sending it

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec#417]
It happens that sometimes, a request errors out and we send the response without having an `ERROR` log. To catch all possible errors, we could check in the `handle_request` function in the front end handler if the response we are about to send is an error or not.

```rust
if response.header.status != Success {
    error!("Sending back an error: {}", response.header.status);
}
```

or something similar.

**Comment by ionut-arm** [comment]
Are you suggesting replacing the other error messages we raise in the providers with this one? Or just adding this on top of the others we already have?

I think it's good to keep the ones we have mostly because it's more easily apparent where they happened. We should maybe review all the paths and try to add logs where we miss them, but a catch-all would also be good.

That log message is also not that comprehensive - we don't copy across the old error when we convert to `ResponseStatus`, so we just end up not knowing why we got it in the first place.

**Comment by MattDavis00** [comment]
I'll work on this
