### ISSUE TITLE
TPM Provider does not persist generated keys accross reboot

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec#504]
It was observed, first [on Slack](https://cloud-native.slack.com/archives/C01EARH2ZB3/p1629301711068400) that keys generated in the TPM provider can not be used after a cold reboot of the system. When trying to use the key generated before (for example export the public part) the following error is seen:

```
Aug 20 12:07:35 parsec[646]: ERROR:esys:../tpm2-tss-2.4.3/src/tss2-esys/api/Esys_ContextLoad.c:93:Esys_ContextLoad() Esys Finish ErrorCode (0x000001df)
Aug 20 12:07:35 parsec[646]: [ERROR tss_esapi::context::tpm_commands::context_management] Error in loading context: integrity check failed (associated with parameter number 1)
```

After investigation on the Slack thread linked above, on the TPM Dev chat ([logs](https://github.com/parallaxsecond/parsec/files/7047442/tpm_dev_log.txt)) and [this post](https://developers.tpm.dev/posts/16453593), the root cause was found.

Although the Storage Primary Seed stays the same accross TPM Reset (which happens when there is a cold system reboot), the key contexts created from the Storage Primary Key are invalidated.

This is for example written at section 30.4 of the Part 1 (Architecture) of the specs:

> All saved object contexts are invalidated by TPM Reset.

Also in section 30.1:

> Saved contexts for all objects and sessions are invalidated on a TPM Reset.

As said in the TPM Dev chat, a better solution to save persistent keys in to store the result of the `tpm2_create` operation which are the `TPM2B_PRIVATE` and `TPM2B_PUBLIC` structure. When the key needs to be used again, those structures can be loaded in the TPM with a `tpm2_load`. See [here](https://github.com/parallaxsecond/rust-tss-esapi/blob/47873ce76af5c879618df82a764d6cab82a314bd/tss-esapi/src/abstraction/transient.rs#L98) for what we currently do when creating a key.

This is a bug as it means that anyone having keys stored in the TPM provider would lose them after a reboot.
This is a stability concern as by changing the way we represent TPM keys in memory we would invalidate old format.

This isssue is made discuss solutions and start a fix!

**Comment by hug-dev** [comment]
I like the version 1 you describe and is probably something we should have added from the start. This is especially true for the TPM provider where we don't only serialise an integer but big data structures that can change. This is something that was also suggested by @MattDavis00 in his design.

Concretely, we need to serialise the `TPM2B_PUBLIC` and the `TPM2B_PRIVATE` structures on disk. We can choose to either serialise the Rust or the C versions of those structure. The Rust version of `TPM2B_PUBLIC` is not currently available as it is being done [here](https://github.com/parallaxsecond/rust-tss-esapi/pull/241). For stability purposes, it might be better to use the C version as it is specified by the TSS specs.

**Comment by Superhepper** [comment]
I guess we are limited to the context methods we have implemented so far. But otherwise it could be possible to use ```Esys_Duplicate``` I think in order to backup the key some where else.

**Comment by ionut-arm** [comment]
> Concretely, we need to serialise the TPM2B_PUBLIC and the TPM2B_PRIVATE structures on disk. We can choose to either serialise the Rust or the C versions of those structure. The Rust version of TPM2B_PUBLIC is not currently available as it is being done here. For stability purposes, it might be better to use the C version as it is specified by the TSS specs.

The private part of the key is trivial to store because it's just a buffer with bytes (and we've already created native types for it). But I don't think we actually need to store the whole `TPM2B_PUBLIC`, because we already store the key attributes alongside that serialized data, and given those attributes we can reconstruct the rest of the fields (i.e. not the public key material) in `TPM2B_PUBLIC`. I'd suggest just having two buffers of bytes, one for the encrypted private part and one for the public part of the key. Then when loading it for use, we reconstruct the public structure (whether using a native solution or the FFI type). This ensures that what we store doesn't depend on what `bindgen` produces.

**Comment by ionut-arm** [comment]
Ok, writing an update note just to keep track of what I've been working on and what issues I've hit.

Refactoring the TPM stack to work as I've highlighted above wasn't that difficult and most of the changes fell into the `tss-esapi` crate as internal changes to the `TransientKeyContext`. The `create_key` and `import` methods now gives out a different structure, `KeyMaterial`, that holds the public and private parts of the keys. All other methods take in this new structure along with the key parameters (an equivalent of `Attributes`) and loads the keys before using them (followed by a flushing of their contents).

Implementing the migration part (i.e. converting our old key context structures to `KeyMaterial`) was more painful. This is because some of the operations (namely, retrieving the private part of the old keys and loading key pairs) require identical public parameters for both the primary key (which we use as a storage key for client keys) and for the client keys as well, across the migration. Ensuring this is the case (and identifying this as an issue in a number of bugs) was non-trivial.

A few problems persist and are next on my TODO list: some of the newer code bits in the `tss-esapi` crate do not compile under the Rust 1.43 compiler. We don't have any written test to check what happens over a TPM Reset.

I'll be updating this comment as work progresses.
