### ISSUE TITLE
Create script for Quickstart package

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec#534]
Official [Github releases](https://github.com/parallaxsecond/parsec/releases) of the service contain a tar gzip file used for quickstart testing. The contents and steps are described in the [Quickstart guide](https://parallaxsecond.github.io/parsec-book/getting_started/linux_x86.html). The process of generating the `.tar.gz` is currently manual, but a script could be included for easier processing in the future.

If we're confident enough, we could even make use of Github Actions to completely automate it.

**Comment by anta5010** [comment]
parsec-cli-tests.sh can be included into the archive and be mentioned in the Quickstart guide

**Comment by mohamedasaker-arm** [comment]
@anta5010 I wonder if we can modify the packaged parsec-cli-tests.sh. more precisely this line 

`PARSEC_SERVICE_ENDPOINT="${PARSEC_SERVICE_ENDPOINT:-unix:/run/parsec/parsec.sock}"`

The reason is, that in the release package parsec uses the socket path ./parsec.sock and I think unifying the default socket path would enhance the OOB experience.
Please share your insights

**Comment by anta5010** [comment]
> @anta5010 I wonder if we can modify the packaged parsec-cli-tests.sh. more precisely this line
> 
> `PARSEC_SERVICE_ENDPOINT="${PARSEC_SERVICE_ENDPOINT:-unix:/run/parsec/parsec.sock}"`
> 
> The reason is, that in the release package parsec uses the socket path ./parsec.sock and I think unifying the default socket path would enhance the OOB experience. Please share your insights

Sorry, I don't understand what you mean by "the release package parsec uses the socket path ./parsec.sock".

Parsec service built from sources uses `/run/parsec/parsec.sock` by default. See https://github.com/parallaxsecond/parsec/blob/87852b7723ffffc63b6266a601a99579e13ae768/src/front/domain_socket.rs#L23

And the same parameter value is used by default in the default Parsec config file. See https://github.com/parallaxsecond/parsec/blob/87852b7723ffffc63b6266a601a99579e13ae768/config.toml#L52

So, most likely you're using a Parsec config file where `socket_path` is set to a non-default value for whatever reason. I think instead of changing  parsec-cli-tests.sh you can either:
- fix the config file you're using to use the default value or
- set PARSEC_SERVICE_ENDPOINT env variable to a non-default value you require. For example `PARSEC_SERVICE_ENDPOINT='./parsec.sock' parsec-cli-tests.sh`

**Comment by mohamedasaker-arm** [comment]
@anta5010 
yes, indeed as it's mentioned [here](https://parallaxsecond.github.io/parsec-book/getting_started/linux_x86.html#using-the-parsec-tool)
It is a non-default path
I was just thinking when someone tries to run the script, then he needs to set PARSEC_SERVICE_ENDPOINT.
Do you think we need to add a section after [this](https://parallaxsecond.github.io/parsec-book/getting_started/linux_x86.html#using-the-parsec-tool)  for the script ?

**Comment by ionut-arm** [comment]
You have the freedom to alter the `parsec-cli-tests.sh` script in this quickstart package script, so you can just do a good ol' search-and-replace, and set the path in the script to whatever you need!

**Comment by anta5010** [comment]
@mohamedasaker-arm I still don't understand your issue. Could you explain it for me.
The script behavior is the same as parset-tool. It uses  PARSEC_SERVICE_ENDPOINT if defined or lets parsec-tool to use the default path. I don't see any reason to change the script to a non-default value. The scripts is already used in testings which would be broken. Please use PARSEC_SERVICE_ENDPOINT
I also don't quire understand why do you use a non-default value in your environment. Don't we want to have a quickstart sandbox be as close to real-world deployments as possible?

And please-please do not change the script. I don't want to have two different versions of the same scripts in different repos. It will be a nightmare to support and sync.
You're welcome to add instructions for `parsec-cli-tests.sh` to the quick guide of course.

**Comment by mohamedasaker-arm** [comment]
Let's first tackle this question 
"Why do you use a non-default value in your environment. Don't we want to have a quickstart sandbox be as close to real-world deployments as possible?" 
In order to use the default path without [securely](https://parallaxsecond.github.io/parsec-book/parsec_service/install_parsec_linux.html) installing parsec
- Create or make sure that the `/run/parsec` path exists
- Change the owner of the folder

`sudo mkdir /run/parsec`
`sudo chown parsec /run/parsec`
`sudo chmod 755 /run/parsec`

The current quickstart package uses a _non-default_ path to avoid those steps @ionut-arm correct me, please!

Regarding this statement "I don't want to have two different versions of the same scripts in different repos. It will be a nightmare to support and sync."
Practically, the edits won't end up in any repo. However, it's a change and might need to be synced If the env variable name has changed.

I don't think the `PARSEC_SERVICE_ENDPOINT` will change regularly, but indeed this change will require a sync if it happens.

If the script is packaged as it is, then before using the script user has to set the environment variable `PARSEC_SERVICE_ENDPOINT`.
